JavaScript. Homework 3
VioletaScvortova/Frontend-Project-KMarketer pull request #7
Opened 2023-09-11 12:53 UTC by VioletaScvortova

Good Day! ☀️ 

Below is a screenshot of my homework №3. Great and very interesting tasks! There was a lot to think about, and it was very good practice for me.

![JS_ Homework 3](https://github.com/VioletaScvortova/Frontend-Project-KMarketer/assets/141768669/278a9b54-988e-4cdb-bf63-8acb37192fee)

2023-09-11 14:54 UTC, sdmnc approved these changes
The only issue I see there is only switch and ternary and no if else expressions

2023-09-11 15:07 UTC, VioletaScvortova commented
> The only issue I see there is only switch and ternary and no if else expressions

if I understood correctly, there is no need to use if and else in switch statement and ternary oparator

2023-09-11 15:15 UTC, IvanCeban requested changes
Well done!
A couple of optimization notes

2023-09-12 20:25 UTC, VioletaScvortova commented on JavaScript homeworks/homework-3.js
> +function calculateDogAge(X) {
Done! Replaced  X with humanAge

2023-09-12 20:37 UTC, VioletaScvortova commented on JavaScript homeworks/homework-3.js
> +    let yourFuture = "You will be a " + X + " in " + Y + ", and will get married to " + Z + " with " + N + " kids"
Fixed it! Thank you, this way is much more convenient

2023-09-12 21:40 UTC, VioletaScvortova commented
@IvanCeban Hi! I`ve made fixes based on comments and added a bonus task with the Arrow function as well
![Screenshot_2](https://github.com/VioletaScvortova/Frontend-Project-KMarketer/assets/141768669/07f92446-77eb-4ea4-a906-d19e82399806)

2023-09-13 13:10 UTC, IvanCeban approved these changes

2023-09-13 13:21 UTC, merged